### PR TITLE
Re-organization

### PR DESCRIPTION
**Pull request by WEKarnesky**
Updated the Java Version and reorganized files. This is essential for some of the changes done in the main Solaris Skunkwerks repo that was accepted that makes it easier for new people to get started helping.

### CODE REVIEW

**Comment by WEKarnesky** [comment]
This now also includes a major security fix to the way XML files are loaded.  Commit 6ae74cd has more details.

**Comment by bcompter** [comment]
Thanks so much for jumping into the project. How did you find us?

**Comment by WEKarnesky** [comment]
> Thanks so much for jumping into the project. How did you find us?

I've been playing battletech and using SSW for years.  I have always wanted to see SSW updated, it just took me time to build a team that's willing to help.

If you are willing to give me permissions to this (and the sister) repositories, we are willing to work on it instead of my fork, but we honestly weren't sure if you were still active at all when we started and didn't want upstream to be an impediment to making progress.

Some notes about the recent commits:

e9de80e is a fix to a security issue, that is very similar to the way that I talked about earlier.

6a253d7 fixes the calculation for the CT structure.  for some reason between the latest release and the code in this section the calculation changed from `Tonnage / 5 - 2` to `(Tonnage - 100) / 5 - 1` which broke the loading of certain mechs.  As a quick fix we reverted the calculation.

b3a9b5f fixes an unreported error that happens when you try to load a fixed Omnimech, but don't have any pods yet.

**Comment by WEKarnesky** [comment]
eac714f fixes a BV calculation issue that gave a discount to all streak missiles when it is only supposed to apply to streak SRMs

**Comment by WEKarnesky** [comment]
@bcompter Thank you for inviting me to the org, but I can't merge the branches because I don't have write access, Do you mind giving me more access so I can manage it?

**Comment by bcompter** [comment]
Just updated your permissions.  Let me know if you are good to go!

**Comment by WEKarnesky** [comment]
Looks like it, thanks!

**Comment by Algebro7** [comment]
Thanks for letting us help. @bcompter, are you willing to add me to the organization as well? @WEKarnesky and I have been working closely together on this and I think it'll be helpful if I'm part of the organization too.

**Comment by bcompter** [comment]
I'm pretty sure I sent you an invite as well. I'll double check on my end.

**Comment by Algebro7** [comment]
Ah I see it now, thanks!

**Pull request merged**
